apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: msp-api
  name: msp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msp-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: msp-api
    spec:
      containers:
      - image: degops.azurecr.io/msp-api:development-a1234567-1500000000
        name: msp-api
        ports:
        - containerPort: 16000
        resources: {}
status: {}
