---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: msp-api
  namespace: msp
spec:
  path: ./kustomize/api/staging

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: msp-api
  namespace: msp
spec:
  filterTags:
    extract: $ts
    pattern: '^staging-[a-f0-9]+-(?P<ts>[0-9]+)'

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: msp-api
  namespace: msp
spec:
  update:
    path: ./kustomize/api/staging
    strategy: Setters