---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: msp
  namespace: msp
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: github-msp-deploy
  url: https://github.com/tnpugi/msp-deploy.git

