---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: msp-ui
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: msp-ui
    namespace: msp
  interval: 1m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: msp
  targetNamespace: msp
  timeout: 3m0s
  validation: client

