apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: msp-api
  name: msp-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - image: degops.azurecr.io/msp-api:staging-a1234567-1700000000 # {"$imagepolicy": "msp:msp-api"}
          name: msp-api
          ports:
            - containerPort: 16000
          resources: {}
status: {}
