apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: msp-api
  name: msp-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - image: degops.azurecr.io/nginx
          tag: main-f12345654-1619182001 # {"$imagepolicy": "msp:degops-nginx:tag"}
          name: msp-api
          ports:
            - containerPort: 16000
          resources: {}
status: {}
