apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: msp-api
  name: msp-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: degops.azurecr.io/nginx:latest # {"$imagepolicy": "msp:degops-nginx"}
        name: msp-api
        ports:
        - containerPort: 16000
        resources: {}
status: {}
patchesStrategicMerge: 
- kustomization-api-staging.yaml
- kustomization-ui-staging.yaml