apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: msp-api
  name: msp-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: degops.azurecr.io/nginx
        tag: latest # {"$imagepolicy": "flux-system:degops-nginx:tag"}
        name: msp-api
        ports:
        - containerPort: 16000
        resources: {}
status: {}
