apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: msp-ui
  name: msp-ui
spec:
  ports:
  - name: "16000"
    port: 16000
    protocol: TCP
    targetPort: 16000
  selector:
    app: msp-ui
  type: NodePort
status:
  loadBalancer: {}
